### ISSUE TITLE
Tree view not updated upon creation

### ISSUE THREAD

**Issue by daneryl** [KETSE/casebox#10]
When creating folders or items on templates subfolder the left-most tree view is not being updated.

**Comment by smugderby** [comment]
The leftmost tree view needs you to right click and choose 'Reload'.

**Comment by txau** [comment]
Still I think it would be great if it just would update without needing to do that. We should totally add that to the backlog.

**Comment by oburlaca** [comment]
FYI, the fix @tvitalie works as follows:
when you create/update an item, Casebox will search for the parent node in the left tree and reload it.

More info:
Since the tree can display also virtual nodes, it's not always clear what nodes to reload when you update and item, this is something to be addressed in the future. 
At this moment, the tree will reload the "physical" parent of the item.

To give you an example when the reload will NOT happen:
there is a virtual folder to display a list of product by country for ex. when you add a new product in "France", the /Products/France/ folder will not reload, because it's virtual.

This is not well documented right now, but here is the config of the FacetedNavigation plugin that can be used to build virtual nodes.:
https://www.casebox.org/dev/docs/tree-facetednav/


Closing the issue.
