### ISSUE TITLE
The 'review' pane shows YES for checkbox type fields no matter what you select

### ISSUE THREAD

**Issue by RafaPolit** [KETSE/casebox#12]
On the review pane, both on the right side of the GUI or when you 'float' the view shows YES for every checkbox field, no matter what you have selected.

Perhaps there is a config problem I'm missing when creating checkboxes? (I believe these are not even documented on the docs, so I'm running a bit blind on the configurations).

Thanks in advance,
Rafa.

**Comment by oburlaca** [comment]
Although @tvitalie fixed it, we'll be reviewing the field types and document only those that will remain.
Instead of 'CheckBox' I'd use a more general 'Objects' field: linked to a thesauri with two values "Yes" and "No".
Checkbox implementation is a hard-coded type of field. issue will be closed once code is committed to master.
