### ISSUE TITLE
Items created after 50 records are put on page 2 no matter the sorting criteria

### ISSUE THREAD

**Issue by RafaPolit** [KETSE/casebox#15]
## General description
If I have 50 items created inside a Template with a sorting criteria like 'order', the newly created items are pushed to page 2 even if their sorting order would put them on page 1, which seems confusing as you would expect the new item in its 'correct' location.

## Way to reproduce
- Have a template with 50 items ordered by reverse order and have them ordered from 1 to 50.  Item 50 would be first, 49 second and so on.
- Create a new item and put in the order field value 51.  This should put it first on the first page, instead, it gets created on page 2.  If you reload the page, it gets correctly sorted on page 1.

Best regards,
Rafa.

**Comment by oburlaca** [comment]
@RafaPolit, we've discussed this issue over skype:
Casebox sorts a column in two ways:
1. Columns indexed in SOLR: Casebox asks SOLR to sort search result
2. if the column is not indexed in SOLR, then sorting is done in PHP after search results are fetched from SOLR

The problem with point n2: pagination & sorting doesn't work ok, because we first retrieve 50 records that are sorted by solr (by ID for ex), and only then PHP sorting happens

**Comment by oburlaca** [comment]
The solution is to index columns that requires correct sorting in SOLR.
closing issue

**Comment by RafaPolit** [comment]
Something is not working as expected with this issue.

* I have put Order in Fields Template as solr column and indexed true.
* I have run the solr related scripts: uptade prperated data and reindexed the core

Still no luck.  Here is the current conifguration:
![Image of Configuration](http://www.rafaelpolit.com/clientes/huridocs/OrderConfiguration.jpg)

And here is the resulting page 1 and 2 of sorting by reverse order:
![Image of Page 1](http://www.rafaelpolit.com/clientes/huridocs/OrderInverse_page1.jpg)
![Image of Page 2](http://www.rafaelpolit.com/clientes/huridocs/OrderInverse_page2.jpg)
